### ISSUE TITLE
Build not working with twrp

### ISSUE THREAD

**Issue by hannesrauhe** [xc-racer99/local_manifests#1]
Hi and thanks for your work! :)
I just tried building Android (for the first time) according to your post from https://forum.xda-developers.com/galaxy-s-i9000/i9000-development/aosp-7-1-rom-discussion-t3523073
Unfortunately make fails almost immediately and complains about a missing _...system/bin/mkfs.f2fs required by teamwin_. 

```
PRODUCT_COPY_FILES device/generic/goldfish/data/etc/apns-conf.xml:system/etc/apns-conf.xml ignored.
No private recovery resources for TARGET_DEVICE galaxysmtd
Starting build with ninja
ninja: Entering directory `.'
ninja: error: 'out/target/product/galaxysmtd/system/bin/mkfs.f2fs', needed by 'out/target/product/galaxysmtd/obj/SHARED_LIBRARIES/libbmlutils_intermediates/teamwin', missing and no known rule to make it
make: *** [ninja_wrapper] Error 1
```
I removed use_twrp.xml and it builds. I guess something is missing to use twrp. Do you have any idea?

**Comment by xc-racer99** [comment]
Yep, that's because the Omni devs broke compatability with AOSP - if you revert commit e7c885655525daabfae8637dfbb8018f7f64a1de (recovery: adjust mkfs.f2fs location) in TWRP then things should build properly.  Since the recovery is built and flashed as part of the kernel, you probably want to keep building it.

**Comment by hannesrauhe** [comment]
Thanks, additionally I had to set TW_THEME before building. `make recovery` is working now.
There are a few more problems with the build. I'll try to figure it out myself, but maybe I get back to you. :-]
